flush ruleset

define WAN       = "enx00e04c680469"

define VLAN10_IF  = "vlan10"     # VLAN10
define VLAN20_IF = "vlan20"   # VLAN20 tagged interface


define VLAN10_NET = 10.0.10.0/24
define VLAN20_NET = 10.0.20.0/28

table inet filter {
  chain input {
    type filter hook input priority 0;
    policy drop;

    iif "lo" accept
    ct state established,related accept
    ip protocol icmp accept

    # SSH only from management (VLAN10)
    iifname $VLAN10_IF tcp dport 22 accept
    iifname $WAN tcp dport 22 accept
    # DHCP Server from Router 
    iifname {$VLAN10_IF, $VLAN20_IF} udp dport {67, 68} accept     

  }

  chain forward {
    type filter hook forward priority 0;
    policy drop;

    # LANs -> Internet
    iifname $VLAN10_IF  oifname $WAN accept
    iifname $VLAN20_IF oifname $WAN accept
    
    # return traffic
    iifname $WAN oifname $VLAN10_IF  ct state established,related accept
    iifname $WAN oifname $VLAN20_IF ct state established,related accept
  }

  chain output {
    type filter hook output priority 0;
    policy accept;
  }
}

table ip nat {
  chain postrouting {
    type nat hook postrouting priority 100;

    oifname $WAN ip saddr $VLAN10_NET masquerade
    oifname $WAN ip saddr $VLAN20_NET masquerade

  }
}
