flush ruleset

define WAN       = "enx00e04c680469"

define VLAN10_IF  = "vlan10"     # VLAN10
define VLAN20_IF = "vlan20"   # VLAN20 tagged interface


define VLAN10_NET = 10.0.10.0/24
define VLAN20_NET = 10.0.20.0/27
define MGMT_PC = 10.0.10.49 # Management PC
define BL_P2S = 10.0.10.10 # Bambulab P2S 3D-printer
define HA = 10.0.20.10 #Home Assistant

table inet filter {
  chain input {
    type filter hook input priority 0;
    policy drop;

    iif "lo" accept
    ct state established,related accept
    ip protocol icmp accept

    # SSH only from management (VLAN10)
    iifname $VLAN10_IF tcp dport 22 accept
    iifname $WAN tcp dport 22 accept
    # DHCP Server from Router 
    iifname {$VLAN10_IF, $VLAN20_IF} udp dport {67, 68} accept     
  }

  chain forward {
    type filter hook forward priority 0;
    policy drop;
  
    # Return traffic (including inter vlan)
    ct state established,related accept
  
    # VLAN10 MGMT-PC -> VLAN20
    iifname $VLAN10_IF oifname $VLAN20_IF ip saddr $MGMT_PC ip daddr $VLAN20_NET accept
    # VLAN20 HomeAssistant -> VLAN10 Bambulab P2S
	iifname $VLAN20_IF oifname $VLAN10_IF ip saddr $HA ip daddr $BL_P2S tcp dport {322, 8883}  accept
  
    # LANs -> Internet
    iifname $VLAN10_IF oifname $WAN accept
    iifname $VLAN20_IF oifname $WAN accept
  
    # return traffic WAN -> VLANs
    iifname $WAN oifname $VLAN10_IF ct state established,related accept
    iifname $WAN oifname $VLAN20_IF ct state established,related accept
  }

  chain output {
    type filter hook output priority 0;
    policy accept;
  }
}

table ip nat {
  chain postrouting {
    type nat hook postrouting priority 100;

    oifname $WAN ip saddr $VLAN10_NET masquerade
    oifname $WAN ip saddr $VLAN20_NET masquerade

  }
}
