network:
  version: 2
  renderer: networkd

  ethernets:
    eth0:
      addresses:
        - 192.168.10.1/24
      dhcp4: no
      dhcp6: no

    enx00e04c680469:
      dhcp4: yes
      dhcp6: no

# Wifi interface is to be disabled
#  wifis:
#    wlan0:
#      dhcp4: no
#      optional: true
