# This is the default routing settings from which the homelab lan is 
# built on.
#
#
#


flush ruleset

define WAN = "enx00e04c680469"
define LAN = "eth0"
define LAN_NET = 192.168.10.0/24

table inet filter {

  chain input {
    type filter hook input priority 0;
    policy drop;

    # Loopback  allowed
    iif "lo" accept

    # Allow established/related
    ct state established,related accept

    # Allow ping to router
    ip protocol icmp accept
    ip6 nexthdr icmpv6 accept

    # Allow SSH from LAN
    iifname $LAN tcp dport 22 accept
  }

  chain forward {
    type filter hook forward priority 0;
    policy drop;

    # Allow return traffic
    iifname $WAN oifname $LAN ct state established,related accept

    # Allow LAN to WAN
    iifname $LAN oifname $WAN accept
  }

  chain output {
    type filter hook output priority 0;
    policy accept;
  }
}

table ip nat {

  chain postrouting {
    type nat hook postrouting priority 100;
    policy accept;

    oifname $WAN ip saddr $LAN_NET masquerade
  }
}
